### ISSUE TITLE
2.Env-Setup/开发环境安装.md 图片显示不出来

### ISSUE THREAD

**Issue by niuhongxing** [shaiic/AI-training#133]
2.Env-Setup/开发环境安装.md 图片显示不出来，检查源文件，发现图片都被链接到本地笔记本上的图片，请修正

**Comment by niuhongxing** [comment]
Ebby你merge这个文档的时候，没有检查图片是否显示正确。

**Comment by ddebby** [comment]
> Ebby你merge这个文档的时候，没有检查图片是否显示正确。

图片文件夹没有上传，已经安排重新上传修复

**Comment by ddebby** [comment]
Fix
