### ISSUE TITLE
更新教师教案和学生手册

### ISSUE THREAD

**Issue by ddebby** [shaiic/AI-training#23]

**Comment by Frank-Li-Fang** [comment]
lesson 01,02,03 update in Jun, 19, 2019.

**Comment by Frank-Li-Fang** [comment]
[lesson 04 - 智能家居](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson04-深度学习.01-定制化(智能家居)) and [lesson 04 - 看图识熊](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson04-深度学习.01-定制化(看图识熊)) update in Jun,23, 2019.

**Comment by Frank-Li-Fang** [comment]
神经网络[lesson 05 - 基础知识](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson05-深度学习.02-基础知识) and [lesson 05 - 线性规划](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson05-深度学习.03-线性规划) update in Jun 30 2019.

**Comment by Frank-Li-Fang** [comment]
神经网络[lesson 06 - 线性分类](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson06-深度学习.04-线性分类) and [lesson 06 - 非线性回归](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson06-深度学习.05-非线性回归) update in Jul 10 2019.

**Comment by Frank-Li-Fang** [comment]
专题讲座[lesson 07 - 强化学习](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson07-强化学习) and [lesson 07 - 自然语言处理](https://github.com/shaiic/AI-training/tree/master/1.Notebooks/4.Lesson-Docs/lesson07-自然语言处理) update in Jul 20 2019.

**Comment by Frank-Li-Fang** [comment]
课程更新完毕
